# Mini-Molecule Foundation — single entrypoint for all four parts.
# Recipes are added by later foundation tasks: gen, check-gen, dev, build, check.

# List available recipes (default).
default:
    @just --list

# Regenerate the web's TypeScript contract type from the Rust contract (SSOT).
gen:
    #!/usr/bin/env bash
    set -euo pipefail
    out="$(mktemp -d)"
    cargo rustc -p contract --no-default-features --features codegen \
        --target wasm32-unknown-unknown --crate-type cdylib
    wasm-bindgen --target bundler --out-dir "$out" --out-name contract \
        target/wasm32-unknown-unknown/debug/contract.wasm
    mkdir -p web/src
    {
        echo "// @generated by \`just gen\` — do not edit"
        cat "$out/contract.d.ts"
    } > web/src/contract.gen.ts
    rm -rf "$out"
    echo "wrote web/src/contract.gen.ts"

# Drift guard: regenerate and fail if the committed type is stale (SC-4).
check-gen:
    #!/usr/bin/env bash
    set -euo pipefail
    just gen
    if ! git diff --exit-code -- web/src/contract.gen.ts; then
        echo "ERROR: web/src/contract.gen.ts is stale — run \`just gen\` and commit." >&2
        exit 1
    fi
    echo "contract.gen.ts is up to date"
