// @generated by `just gen` — do not edit
/* tslint:disable */
/* eslint-disable */
/**
 * The molecule\'s self-description — the spine every later rung extends.
 */
export interface SelfId {
    id: string;
    name: string;
    fw_version: string;
    capabilities: string[];
}

